//! Embedded live System Graph web view for Darkstar.
//!
//! THIS IS VERY IMPORTANT!!!
//! ==========================================
//! AUTHOR: M. SZUL
//! AI MODEL: GPT-5.6 Luna
//! TIMESTAMP: 2026-08-27 22:50:00
//! REASON FOR CREATION: Provide an n8n-like browser view where a human can inspect the architecture and watch a real Darkstar run move through its nodes.
//! MECHANICS: Serves one self-contained HTML document. The viewer loads the authenticated architecture snapshot, starts an explicit demo run, then reads its authenticated SSE stream with Fetch and highlights nodes as execution events arrive.
//! SYSTEM PART: Darkstar Server / System Graph UI
//! ARCHITECTURE FUNCTION: Human-facing execution inspector; read-only with respect to tools and security policy.
//! DEPENDENCIES/LINKS: darkstar-core::system_graph, /v1/system-graph, /v1/runs/start, /v1/runs/{run_id}/events; browser Fetch API and SVG.
//! TECH STACK: Rust 2024 + embedded HTML/CSS/vanilla JavaScript; selected to keep the headless container small and avoid a second frontend build system at this stage.
//! LOCAL WORKSPACE: N/A - GitHub-first workspace.
//! GIT COMMIT: PENDING
//! GITHUB METADATA: jpytka666-jpg/polip-agi, branch feat/darkstar-system-graph
//! ==========================================

pub const SYSTEM_GRAPH_HTML: &str = r##"<!doctype html>
<html lang="pl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Darkstar Live Run Graph</title>
<style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,Segoe UI,sans-serif}body{margin:0;background:#050812;color:#e9f2ff;overflow:hidden}header{height:58px;display:flex;gap:8px;align-items:center;padding:0 14px;border-bottom:1px solid #203049;background:#09111f}input,button{background:#0d1829;color:#e9f2ff;border:1px solid #29415f;border-radius:8px;padding:8px 10px}input{min-width:210px}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}main{display:grid;grid-template-columns:1fr 340px;height:calc(100vh - 59px)}#canvas{position:relative;overflow:hidden;background:radial-gradient(circle at 50% 40%,#10243a 0,#070c16 45%,#03050a 100%)}svg{width:100%;height:100%;touch-action:none}.edge{stroke:#355b78;stroke-width:1.5;opacity:.7}.edge.live{stroke:#7ee7ff;stroke-width:4;filter:drop-shadow(0 0 8px #4ad9ff);opacity:1}.node{cursor:pointer}.node circle{stroke:#d6ecff;stroke-width:1.5;fill:#21445d}.node.repository circle{fill:#1f7a9e}.node.runtime circle{fill:#745320}.node.file circle{fill:#274f6c}.node.active circle{filter:drop-shadow(0 0 7px #3ca7d9)}.node.running circle{fill:#8b6d2e;filter:drop-shadow(0 0 11px #ffc95c)}.node.success circle{fill:#2f7a5a;filter:drop-shadow(0 0 10px #65e7a2)}.node.allow circle{fill:#2f7a5a;filter:drop-shadow(0 0 10px #65e7a2)}.node.selected circle{stroke-width:3;filter:drop-shadow(0 0 10px #fff)}.node text{fill:#eef7ff;font-size:11px;pointer-events:none}aside{background:#08101d;border-left:1px solid #203049;padding:14px;overflow:auto}h1{font-size:16px;margin:0 0 10px}.muted{color:#7e97af;font-size:12px}pre{white-space:pre-wrap;word-break:break-word;color:#b9cce0;font-size:12px}.pill{display:inline-block;border:1px solid #29415f;border-radius:999px;padding:2px 7px;margin:2px;font-size:11px}.log{margin:5px 0;padding:7px;border-left:2px solid #29415f;background:#0b1625;font-size:11px}.log b{color:#dbeeff}.runbar{font-size:12px;color:#9eb7ce;padding:3px 4px 7px}.legend{font-size:11px;color:#6f879d;margin-top:12px;line-height:1.5}
+</style></head>
<body>
<header><strong>Darkstar / Live Run</strong><input id="token" type="password" placeholder="DARKSTAR_API_TOKEN"><button id="load">Wczytaj</button><button id="start">Start Demo Run</button><button id="reset">Reset</button><input id="q" placeholder="szukaj"></header>
<main><div id="canvas"><svg id="svg" viewBox="0 0 1200 800"><g id="world"></g></svg></div><aside><div class="runbar" id="run">Brak aktywnego runu.</div><h1>Inspektor</h1><div id="status" class="muted">Podaj token i kliknij „Wczytaj”.</div><div id="details"></div><h1>Live log</h1><div id="log"></div><div class="legend">Przeciąganie = mapa. Kółko = zoom. Klik node = szczegóły. Zielony = sukces/allow. Złoty = aktywny krok. Niebieski = architektura.</div></aside></main>
<script>
const svg=document.getElementById('svg'),world=document.getElementById('world'),status=document.getElementById('status'),details=document.getElementById('details'),log=document.getElementById('log'),runLabel=document.getElementById('run'),tokenEl=document.getElementById('token');let data=null,scale=1,tx=0,ty=0,drag=null,currentRun=null,liveNode=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function layout(d){const groups={};d.nodes.forEach(n=>(groups[n.system||'Other']??=[]).push(n));const systems=Object.entries(groups);const gap=systems.length>1?980/(systems.length-1):0,pos={};systems.forEach(([system,nodes],i)=>{const x=120+i*gap;nodes.sort((a,b)=>(a.last_modified_at||'').localeCompare(b.last_modified_at||''));const step=Math.max(48,600/Math.max(nodes.length,1));nodes.forEach((n,j)=>pos[n.id]={x,y:80+j*step});});return pos}
function render(d){world.innerHTML='';const pos=layout(d),byId=Object.fromEntries(d.nodes.map(n=>[n.id,n]));d.edges.forEach(e=>{const a=pos[e.from],b=pos[e.to];if(!a||!b)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class','edge');line.dataset.edge=`${e.from}->${e.to}`;world.appendChild(line)});d.nodes.forEach(n=>{const p=pos[n.id],g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class',`node ${n.kind} ${n.status}`);g.dataset.id=n.id;g.setAttribute('transform',`translate(${p.x},${p.y})`);const c=document.createElementNS('http://www.w3.org/2000/svg','circle');g.appendChild(c);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',n.kind==='file'?18:25);t.setAttribute('y',4);t.textContent=n.name;g.appendChild(t);g.onclick=()=>inspect(n,byId);world.appendChild(g)});applySearch();status.textContent=`${d.snapshot_id} · ${d.nodes.length} węzłów · ${d.edges.length} relacji`}
function applySearch(){const q=document.getElementById('q').value.trim().toLowerCase();[...world.querySelectorAll('.node')].forEach(el=>{const n=data?.nodes.find(x=>x.id===el.dataset.id);el.style.display=!q||JSON.stringify(n).toLowerCase().includes(q)?'':'none'})}
function inspect(n,byId){world.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));world.querySelector(`[data-id="${CSS.escape(n.id)}"]`)?.classList.add('selected');const rel=data.edges.filter(e=>e.from===n.id||e.to===n.id);details.innerHTML=`<div class="pill">${esc(n.kind)}</div><div class="pill">${esc(n.status)}</div><h1>${esc(n.name)}</h1><pre>${esc(JSON.stringify(n,null,2))}</pre><h1>Relacje</h1>${rel.map(e=>{const other=byId[e.from===n.id?e.to:e.from];return `<div class="muted">${esc(e.kind)} → ${esc(other?.name||'?')}</div>`}).join('')}`}
function setLiveNode(nodeId,statusValue){if(liveNode){liveNode.classList.remove('running','success','allow','selected');}liveNode=world.querySelector(`[data-id="${CSS.escape(nodeId)}"]`);if(!liveNode)return;liveNode.classList.add(statusValue==='allow'||statusValue==='success'?'success':'running','selected');world.querySelectorAll('.edge.live').forEach(x=>x.classList.remove('live'));if(data&&currentRun){const prior=data.edges.find(e=>e.from===liveNode.dataset.id&&e.to===currentRun.previousNode);if(prior)prior.classList.add('live');}currentRun&&(currentRun.previousNode=nodeId)}
async function loadGraph(){const token=tokenEl.value;if(!token){status.textContent='Brak tokena.';return;}status.textContent='Ładowanie...';try{const r=await fetch('/v1/system-graph',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();render(data);status.textContent='Graf załadowany.'}catch(e){status.textContent=`Błąd: ${e.message}`}}
async function startRun(){const token=tokenEl.value;if(!token){status.textContent='Najpierw podaj token.';return;}if(!data)await loadGraph();if(!data)return;const runId=crypto.randomUUID();currentRun={id:runId,previousNode:null};runLabel.textContent=`RUN ${runId}`;log.innerHTML='';document.getElementById('start').disabled=true;const streamPromise=streamRun(runId,token);try{const r=await fetch('/v1/runs/start',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({run_id:runId})});if(!r.ok)throw new Error(`HTTP ${r.status}`);status.textContent='Run wystartował.';await streamPromise}catch(e){status.textContent=`Błąd runu: ${e.message}`}finally{document.getElementById('start').disabled=false}}
async function streamRun(runId,token){const r=await fetch(`/v1/runs/${runId}/events`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`SSE HTTP ${r.status}`);const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){const line=chunk.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const event=JSON.parse(line.slice(6));handleEvent(event)}}}
function handleEvent(event){setLiveNode(event.node_id,event.status);const item=document.createElement('div');item.className='log';item.innerHTML=`<b>#${event.sequence} ${esc(event.event_type)}</b><br><span>${esc(event.node_id)} · ${esc(event.status)}</span><br><span class="muted">${esc(event.message)}</span>`;log.prepend(item);status.textContent=`${event.event_type} · ${event.status}`;if(event.status==='success'){runLabel.textContent=`RUN ${event.run_id} · COMPLETE`}}
document.getElementById('load').onclick=loadGraph;document.getElementById('start').onclick=startRun;document.getElementById('q').oninput=applySearch;document.getElementById('reset').onclick=()=>{scale=1;tx=0;ty=0;world.setAttribute('transform','translate(0 0) scale(1)');world.querySelectorAll('.selected,.running,.success,.allow').forEach(x=>x.classList.remove('selected','running','success','allow'));world.querySelectorAll('.edge.live').forEach(x=>x.classList.remove('live'));log.innerHTML='';runLabel.textContent='Brak aktywnego runu.'};svg.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.35,Math.min(4,scale*(e.deltaY<0?1.1:.9)));world.setAttribute('transform',`translate(${tx} ${ty}) scale(${scale})`)},{passive:false});svg.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,tx,ty};svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;tx=drag.tx+(e.clientX-drag.x);ty=drag.ty+(e.clientY-drag.y);world.setAttribute('transform',`translate(${tx} ${ty}) scale(${scale})`)});svg.addEventListener('pointerup',()=>drag=null);
</script></body></html>"##;
