# darkstar-header-v1
# po co: Cargo.toml
# nie wolno: hotspot, ruszac wlp2s0, wracac do 10.44, gasic DARKSTAR-WiFi, haslo w gicie
# autor: Marcin
# powstal: 2026-09-04
[package]
name = "darkstar-shadow"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
